// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgH1Uz2gOWdIYb4kdWizSVzHnD3MShCS4',
    appId: '1:13035281684:web:73b9f1a7278a7ae6cdf601',
    messagingSenderId: '13035281684',
    projectId: 'alakhbar-5f66d',
    authDomain: 'alakhbar-5f66d.firebaseapp.com',
    storageBucket: 'alakhbar-5f66d.firebasestorage.app',
    measurementId: 'G-ZG7ZYKSKSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC41hRVqv7gSzUMgsBg_4GE-TIbKEC5FOg',
    appId: '1:13035281684:android:022e0ac2d42e836bcdf601',
    messagingSenderId: '13035281684',
    projectId: 'alakhbar-5f66d',
    storageBucket: 'alakhbar-5f66d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1ihfv3QKTM1w5vq1TqlaOTQQnpN3ii9k',
    appId: '1:13035281684:ios:1bdbfe5219a7e417cdf601',
    messagingSenderId: '13035281684',
    projectId: 'alakhbar-5f66d',
    storageBucket: 'alakhbar-5f66d.firebasestorage.app',
    iosClientId: '13035281684-cnegq8ksem0tgqtvesdu1sg22pg846g5.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsPaperApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1ihfv3QKTM1w5vq1TqlaOTQQnpN3ii9k',
    appId: '1:13035281684:ios:1bdbfe5219a7e417cdf601',
    messagingSenderId: '13035281684',
    projectId: 'alakhbar-5f66d',
    storageBucket: 'alakhbar-5f66d.firebasestorage.app',
    iosClientId: '13035281684-cnegq8ksem0tgqtvesdu1sg22pg846g5.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsPaperApp',
  );
}
